-- SQL LEARNING ABD REFERENCE - DDL COMMANDS
-- DATA DEFINITION LANGUAGE


--CREATE
-- CREATE A NEW TABLE CALLED 'PERSONS' WITH COLUMNS: ID, PERSONS_NAME, BIRTH_DATE AND PHONE
CREATE TABLE PERSONS (
ID INT NOT NULL, -- ID WILL BE AN INTERGER AND CAN NOT BE NULL
PERSON_NAME VARCHAR (50) NOT NULL, -- PERSON NAME IS VARCHAR AKA CHARECTORS, AND CANT NOT BE NULL
BIRTH_DATE DATE,
PHONE VARCHAR(15) NOT NULL, 
CONSTRAINT PK_PERSONS PRIMARY KEY(ID) -- ESTABLISHING THE PRIMARY KEY
)

SELECT * FROM DBO.PERSONS

-- TO SEE HOW A TABLE WAS CREATED, GO TO TABLE, HIT 'SCRIPT TABLE AS' THEN HIT 'CREATE TO'. THEN 'NEW QUERY EDITOR WINDOW' TO SEE THE WORKINGS OF THE TABLE



-- ALTER
-- EDIT AND CHANGE A TABLE
-- ADD A NEW COLUMN CALLED 'EMAIL' TO THE PERSONS TABLE
ALTER TABLE PERSONS 
ADD EMAIL VARCHAR(50) NOT NULL

SELECT * FROM PERSONS

-- REMOVE THE COULMN PHONE FROM PERSONS
ALTER TABLE PERSONS
DROP COLUMN PHONE 

SELECT * FROM PERSONS



--DROP
-- REMOVE THE TABLE FROM A DATABASE -- DELETES EVERYTHING

--DELETE THE TABLE 'PERSONS' FROM THE DATABASE
DROP TABLE PERSONS


