--- CASE WHEN STATEMENT

--EVALUATES A LIST OF CONDITIONS AND RETURNS A VALUE WHEN THE FIRST CONDITION IS MET
--CASE
	-- WHEN CONDITION1 THEN VALUE1 -- > THE VALUES HAVE TO BE THE SAME DATA TYPE (INT, VARCHAR, ETC.)
	-- WHEN CONDITION2 THEN VALUE2
	-- ELSE -- > A DEFUALT VALUE IF ALL CONDITIONS FAILED
--END


-- ADD IN SALES STATUS INDICATOR (GREATER THAN 50 HIGH, GREATER THAN 20, MEDIUM, UNDER 20 LOW)
-- SORT SALES HIGH TO LOW
SELECT 
ORDERID,
SALES,
CASE
	WHEN SALES > 50 THEN 'HIGH'
	WHEN SALES > 20 THEN 'MEDIUM'
	ELSE 'LOW'
END AS CATEGORY
FROM SALES.Orders
ORDER BY SALES DESC

-- GROUP BY THE CATEGORY TO VIEW TOTAL SALES PER CATERGORY

SELECT
CATEGORY,
SUM(SALES) AS TOTAL_SALES
FROM (
	SELECT 
	ORDERID,
	SALES,
	CASE
		WHEN SALES > 50 THEN 'HIGH'
		WHEN SALES > 20 THEN 'MEDIUM'
		ELSE 'LOW'
	END AS CATEGORY
	FROM SALES.Orders
)t
GROUP BY CATEGORY
ORDER BY SUM(SALES) DESC


--MAPPING VALUES
-- CONVERT ABBREVIATION OR FLAG DATA INTO COMPLETE OR FULL CONTEXT VALUES
-- RETRIEVE EMPLOYEE DETAILS WITH GENDER DISPLAYED AS FULL TEXT
SELECT 
[EmployeeID],
	[FirstName] ,
	[LastName] ,
	[Department] ,
	[BirthDate] ,
	CASE
	WHEN GENDER = 'M' THEN 'MALE'
	ELSE 'FEMALE'
END AS GENDER,
	[Salary] ,
	[ManagerID]
FROM SALES.Employees

-- RETRIEVE CUSTOMER DETAILS WITH ABBREVIATED COUNTRY CODE
SELECT 
CUSTOMERID,
FIRSTNAME,
LASTNAME,
SCORE,
	CASE
		WHEN COUNTRY = 'USA' THEN 'USA'
		WHEN COUNTRY = 'GERMANY' THEN 'DE'
		ELSE NULL
	END AS COUNTRY_ABV
	FROM SALES.Customers

	-- ALTERNATE QUICK FORM
	SELECT 
CUSTOMERID,
FIRSTNAME,
LASTNAME,
SCORE,
	CASE Country --  QUICK FORM
		WHEN 'USA' THEN 'USA'
		WHEN 'GERMANY' THEN 'DE'
		ELSE NULL
	END AS COUNTRY_ABV
	FROM SALES.Customers

-- FIDN THE AVG SCORE OF CUSTOMERS AND TREAT NULLS AS 0
SELECT *,
AVG(CASE SCORE
	WHEN  SCORE THEN Score
	ELSE 0
END) OVER () AS AVG_SCORE
FROM SALES.Customers

-- COUNT HOW MANY TIMES EACH CUSTOMER HAS MADE AN ORDER WITH SALES GREATER THAN 30
SELECT
* 
FROM SALES.Orders;

SELECT 
CUSTOMERID,
SUM(CASE 
	WHEN SALES > 30 THEN 1
	ELSE 0
END) AS SALES_OVER_30,
COUNT(*) AS TOTAL_SALES
FROM SALES.ORDERS
GROUP BY CustomerID
