-- SQL SUBQUERY
-- A QUERY WITHIN A QUERY 

-- RESULT TYPES
--SCALAR SUBQUERY
	-- ONE SINGLE VALUE RESULT
--ROW SUBQUERY
	-- MULITPLE ROWS & ONE COLUMN
-- TABLE SUBQUERY 
	-- MULTIPLE ROWS AND MULTIPLE COLUMNS

--FROM SUBQUERY
	-- used as temporary table for the main query 
-- FIND THE PRODUCTS THAT HAVE A PRICE HIGHER THAN THE AVERAGE PRICE FOR ALL PRODUCTS 

SELECT
PRODUCT,
PRODUCTID,
PRICE,
AVG_PRICE
FROM (
	SELECT 
	*,
	AVG(PRICE) OVER() AS AVG_PRICE
	FROM SALES.Products
)t
WHERE PRICE > AVG_PRICE

-- RANK CUSTOMERS BASED ON THEIR TOTAL AMOUNT OF SALES
SELECT 
*,
RANK() OVER (ORDER BY TOTAL_SALES DESC) AS RANK
FROM(
	SELECT 
	CustomerID,
	SUM(SALES) AS TOTAL_SALES
	FROM SALES.Orders
	GROUP BY CustomerID
)t

-- SELECT CLAUSE
-- USED TO AGGREGATE DATA SIDE BY SIDE WITH THE MAIN QUERY DATA, ALLOWING FOR DIRECT COMPARISON

-- SHOW THE PRODUCT IDS, NAMES, PRICES AND TOTAL NUMBER OF ORDERS
SELECT
*,
(SELECT
COUNT(*)
FROM SALES.Orders) AS TOTAL_#_ORDERS
FROM SALES.Products

-- SUBQUERY IN JOIN CLAUSE
--USED TO PREPARE THE DATA (FILTERING OR AGGREGATION) BEFORE JOINING IT WITH OTHER TABLES

-- SHOW ALL CUSTOMER DETAILS AND FIND THE TOTAL ORDER FOR EACH CUSTOMER
SELECT 
SALES.Customers.*,
ORDER_COUNT
FROM SALES.Customers
LEFT JOIN (
	SELECT
	CUSTOMERID,
	COUNT(*) AS ORDER_COUNT
	FROM SALES.Orders
	GROUP BY CustomerID
)t
ON SALES.CUSTOMERS.CustomerID = t.CUSTOMERID

--SUBQURY IN WHERE CLAUSE
-- USED FOR COMPLEX FILITERING LOGIC AND MAKES QUERY MORE FLEXIBLE AND DYNAMIC

-- FIND THE PRODUCTS THAT HAVE A PRICE HIGHER THAN THE AVERAGE PRICE OF ALL PRODUCT
SELECT 
* 
FROM SALES.Products
WHERE PRICE > (
	SELECT
	AVG(PRICE) AS avg_price
	FROM SALES.Products
	)

-- IN OPERATOR
	-- CHECKS WHETHER A VALUE MATCHES ANY VALUE FROM A LIST

-- SHOW THE DETAILS OF ORDERS MADE BY CUSTOMERS IN GERMANY 

SELECT
* 
FROM SALES.Orders
WHERE CUSTOMERID IN (
	SELECT
	CustomerID
	FROM SALES.Customers
	WHERE COUNTRY = 'GERMANY'
)
-- SHOW THE DETAILS OF ORDERS MADE BY CUSTOMERS NOT IN GERMANY 
SELECT
* 
FROM SALES.Orders
WHERE CUSTOMERID NOT IN (
	SELECT
	CustomerID
	FROM SALES.Customers
	WHERE COUNTRY = 'GERMANY'
)

-- ANY OPERATOR

-- FIND FEMALE EMPLOYEES WHOSE SALARIES ARE GREATER THAN THE SALARIES OF ANY MALE EMPLOYEE
SELECT
*
FROM(
	SELECT * 
	FROM SALES.Employees
	WHERE GENDER = 'F'
)t
WHERE SALARY > ANY (
	SELECT
	SALARY
	FROM SALES.Employees
	WHERE GENDER = 'M'
	)

-- FIND FEMALE EMPLOYEES WHOSE SALARIES ARE GREATER THAN SALARIES OF ALL MALE EMPLOYEES
SELECT
*
FROM(
	SELECT * 
	FROM SALES.Employees
	WHERE GENDER = 'F'
)t
WHERE SALARY > ALL (
	SELECT
	SALARY
	FROM SALES.Employees
	WHERE GENDER = 'M'
	)

-- NON-CORRELATED SUBQUERY
-- A SUBQUERY THAT CAN RUN INDEPENDTLY FROM THE MAIN QUERY 

-- SHOW ALL CUSTOMER DETAILS AND FIND THE TOTAL ORDERS FOR EACH CUSTOMERS

SELECT 
SALES.Customers.*,
t.ORDER_COUNT
FROM SALES.Customers
LEFT JOIN (
SELECT
CUSTOMERID,
COUNT(*)  AS ORDER_COUNT
FROM SALES.Orders
GROUP BY CustomerID
)t
ON SALES.CUSTOMERS.CUSTOMERID = t.CUSTOMERID

--> 
SELECT
*,
(SELECT COUNT (*) FROM SALES.Orders o WHERE o.CUSTOMERID = c.CUSTOMERID) AS TOTAL_SALES
FROM SALES.Customers c

-- EXISTS
-- CHECK IF A SUBQUERY RETURNS ANY ROWS

-- SHOW THE DETAILS OF ORDERS MADE BY CUSTOMERS IN GERMANY

SELECT
*
FROM SALES.Orders o
WHERE EXISTS 
(SELECT 1
FROM SALES.Customers c
WHERE COUNTRY = 'GERMANY'
AND o.CUSTOMERID = c.CUSTOMERID)
