--NUMBER FUNCTIONS
	-- ROUND, ABS

-- ROUND
	-- ROUND(VALUE,#) -> # INDICATES WHAT DECIMAL PLACE TO ROUND UP TO 
SELECT 
3.516,
ROUND(3.516,2) AS ROUND_2,
ROUND(3.516,1) AS ROUND_1,
ROUND(3.516,0) AS ROUND_0

-- ABS
	-- ABSOLUTE
		-- CONVERTS NEGATIVE TO POSITIVE
SELECT
-10,
ABS(-10)