--DML COMMANDS
-- DATA MANIUPLATION LANGUAGE
-- INSERT, UPDATE, DELETE


-- INSERT
-- ADD A NEW ROW TO YOUR TABLE
	--INSTERT INTO TABLE_NAME (COLM1, COLM2,COLM3...) <- IF COLUMNS ARE NOT LISTED, THEN SQL WILL ASSUME YOU ARE ADDING VALUES TO ALL COLUMNS
	--VALUES (VALUE 1,VALUE 2, VALUE 3,...) <- NUMBER OF VALUES MUST MATCH THE NUMBER OF COLUMNS
	-- COLUMNS AND VALUES MUST BE IN THE SAME ORDER
INSERT INTO customers (ID, FIRST_NAME, COUNTRY, SCORE)
VALUES
	(6, 'ANNA','USA',750),
	(7,'SAM','GERMANY',285),
	(8, 'BERT','USA',750),
	(9,'MARY','GERMANY', 800),
	(10,'TONY','USA',NULL)
	(11, 'YUTHGE','USA',NULL),
	(12,'UBHSDBFI','UK', NULL)

SELECT * FROM customers

-- INSERT USING SELECT	
	-- INSERT DATA USING ANOTHER TABLE
-- COPY DATA FROM 'CUSTOMERS' TABLE INTO 'PERSONS'
SELECT * FROM persons
SELECT * FROM customers
INSERT INTO PERSONS (ID, person_name,birth_date,phone)
SELECT 
	ID, 
	FIRST_NAME,
	NULL,
	000
FROM customers



-- UPDATE
-- CHANGE CONTENT OF ALREADY EXISITING ROWS
	-- UPDATE TABLE
		-- SET COLM 1 = VALUE 1,
				--COLUM 2 = VALUE 2
				--WHERE CONDITION

-- CHANGE THE SCORE OF CUSTOMER 6 TO '0'
SELECT * FROM CUSTOMERS
WHERE ID = 6

UPDATE customers
	SET SCORE = 0
	WHERE ID = 6

-- CHANGE THE SCORE OF CUSTOMER WITH ID 10 TO 0 AND UPDATE THE COUNTRY TO 'UK'
SELECT * FROM CUSTOMERS
WHERE ID = 10

UPDATE customers
	SET SCORE = 0,
			COUNTRY = 'UK'
	WHERE ID = 10 

-- UPDATE ALL NULL SCORE TO 0
SELECT * FROM CUSTOMERS 
WHERE SCORE IS NULL

UPDATE customers
	SET SCORE = 0
	WHERE SCORE IS NULL


-- DELETE
	-- REMOVE ROWS FROM THE TABLE
-- DELETE FROM TABLE_NAME
--	WHERE CONDITION <- IF YOU DO NOT ADD A CONDITION, ALL THE ROWS WILL BE DELETED

DELETE FROM customers
WHERE ID > 5

SELECT * FROM customers

-- DELETE ALL DATA FROM PERSONS TABLE
DELETE FROM persons
SELECT * FROM persons
-- ALTERNATIVE, DELETES DATA IN TABLE FASTER THAN THE 'DELETE' FUNCTION
TRUNCATE TABLE PERSONS
