-- SQL VIEWS
-- DATABASE STRUCTURE AND DDL
	-- DDL 
		-- A SET OF COMMANDS THAT ALLOWS US TO DEFINE AND MANAGE THE STRUCTURE OF A DATABASE
			-- CREATE, ALTER, DROP
		-- THE HEIRARCHY/STRUCTURE OF A DATABASE
			-- SERVER
			--DATABASE
			-- SCHEMA
			-- TABLE -- VIEW
			-- COLUMNS
			-- VALUES

	-- THREE LEVEL ARCHITECTURE
	 -- PHYSICAL LEVEL
		-- LOWEST LEVEL, WHERE DATA IS STORED
		-- DATABASE ADMIN
	 -- LOGICAL LEVEL
		--APPLICATION DEVELOPER
		-- DATA ENGINEER
		-- HOW DATA IS STRUCTURED
			-- CREATING TABLES, INDEXES, RELATIONSHIPS, ETC.
	 -- VIEW LEVEL
		--USED BY END USER


-- WHAT ARE VIEWS?
	-- VIRTURAL TABLE BASED ON THE RESULT SET OF A QUERY, WITHOUT STORING THE DATA IN DATABASE.
	-- VIEWS ARE PRESISTED SQL QUERIES IN THE DATABASE IN THE DATABASE

-- TABLES VS VIEWS
	--TABLES HOME DATA
		-- VIEWS ARE VIRTUAL, DONT HOLD DATA
	--VIEWS ARE EASIER TO MAINTAIN
	-- TABLES ARE FASTER THAN VIEWS
		-- VIEWS ARE TWO QUEIRIES
			-- ONE TO POPULATE THE VIEW, AND THE OTHER TO GET RESULTS
	--READ/WRITE WITH TABLES
		-- READ ONLY WITH VIEWS

-- VIEWS VS CTE
 -- CTE REDUCE REFUNDANCY IN 1 QUERY, IMPROVES REUSABILITY IN 1 QUERY, IS TEMPORARY LOGIC, NO MAINTENANCE (AUTO CLEANUP)
	-- VIEWS REDUCE REDUNDANCY IN MULTIPLE QUERIES, IMPROVES REUSABILITY IN MULITPLE QUERIES, PERSISTED LOGIC, NEED TO MAINTAIN (CREATE/DROP) 
--

-- USE CASE 1 - CENTRAL QUERY LOGIC
	-- STORE CENTRAL, COMPLEX QUERY LOGIC IN THE DATABASE FOR ACCESS BY MULTIPLE QUERIES, REDUCING PROJECT COMPLEXITY



-- CREATE / UPDATE/ DROP
-- TO UPDATE A VIEW, YOU WILL HAVE TO DROP IT, THE RECREATE IT WITH ADDED COLUMNS
/* IF OBJECT ('VIEW NAME', 'v') IS NOT NULL
	 DROP VIEW VIEW-NAME;
GO
*/

-- SYNTAX
/*
CREATE VIEW VIEW-NAME AS
	(
	SELECT
	FROM 
	WHERE
	)
*/
-- FIND THE RUNNING TOTAL OF SALES FOR EACH MONTH
CREATE VIEW SALES.V_MONTHLY_SUM_SALES AS
(
SELECT
MONTH(ORDERDATE) AS ORDER_MONTH,
SUM(SALES)  AS MONTHLY_TOTAL_SALES,
COUNT(ORDERID) AS TOTAL_ORDERS,
SUM(QUANTITY) AS TOTAL_QUANTITY
FROM SALES.Orders
GROUP BY MONTH(ORDERDATE)
)

SELECT
ORDER_MONTH,
SUM(MONTHLY_TOTAL_SALES) OVER (ORDER BY ORDER_MONTH) AS RUNNING_TOTAL
FROM SALES.V_MONTHLY_SUM_SALES


-- USE CASE 2 : HIDE COMPLEXITY
	-- PROVIDE A CLEAN VIEW FOR END USERS 

-- EXAMPLE
-- PROVIDE A VIEW THE COMBINES DETAILS FROM ORDERS, PRODUCTS, CUSTOMERS, AND EMPLOYEES


CREATE VIEW SALES.v_ORDER_DETAILS AS (
SELECT 
O.OrderID,
P.Product,
P.Category,
O.OrderDate,
O.Sales,
O.Quantity,
COALESCE(C.FirstName, '')+ ' ' +COALESCE(C.LastName,'') AS CUSTOMER,
C.Country AS CUSTOMER_COUNTRY,
COALESCE(E.FirstName, '')+ ' ' +COALESCE(E.LastName,'') AS EMPLOYEE,
E.Department
FROM SALES.Orders o
LEFT JOIN SALES.Products p
ON o.ProductID = p.ProductID
LEFT JOIN SALES.Customers c
ON o.CustomerID = c.CustomerID
LEFT JOIN Sales.Employees e
ON o.SalesPersonID = e.EmployeeID
)

--USE CASE 3: SECURITY
-- USE A VIEW TO ENFORCE SECURITY AND PROTECT SENSITVE DATA, BY HIDING COLUMNS AND/OR ROWS FROM TABLES.
-- CAN RESTRICT WHAT COLUMNS AND/OR WHAT ROWS CAN BE SEEN BY CREATING VIEWS 


-- EXAMPLE: PROVIDE A VIEW FOR THE EU SALES TEAM THAT COMBINES DETAILS FROM ALL TABLES AND EXCLUDES DATA RELATED TO THE USE

CREATE VIEW SALES.EU_ORDERS_DETAILS AS (
SELECT 
O.OrderID,
P.Product,
P.Category,
O.OrderDate,
O.Sales,
O.Quantity,
COALESCE(C.FirstName, '')+ ' ' +COALESCE(C.LastName,'') AS CUSTOMER,
C.Country AS CUSTOMER_COUNTRY,
COALESCE(E.FirstName, '')+ ' ' +COALESCE(E.LastName,'') AS EMPLOYEE,
E.Department
FROM SALES.Orders o
LEFT JOIN SALES.Products p
ON o.ProductID = p.ProductID
LEFT JOIN SALES.Customers c
ON o.CustomerID = c.CustomerID
LEFT JOIN Sales.Employees e
ON o.SalesPersonID = e.EmployeeID
WHERE c.Country != 'USA'
)

SELECT *
FROM SALES.EU_ORDERS_DETAILS


-- CASE USE: CAN BE USED AS DATA MARTS IN DATA WAREHOUSE SYSTEMS BECAUSE THEY PROVIDE A FLEXIBLE AND EFFICIENT WAY TO PRESENT DATA.
