-- AGGREGATE FUNCTIONS

-- TOTAL NUMBER OF ORDERS
SELECT
COUNT(*) AS NUMBER_OF_ORDERS
FROM SALES.Orders

-- TOTAL NUMBER OF SALES?
SELECT
SUM(SALES) AS TOTAL_SALES
FROM SALES.ORDERS

-- AVG SALES?
SELECT
AVG(SALES) AS AVG_SALES
FROM SALES.Orders

--MAX SALES?
SELECT
MAX(SALES) AS MAX_SALE
FROM SALES.Orders

-- MIN SALE?
SELECT
MIN(SALES) AS MIN_SALE
FROM SALES.Orders
