-- SET OPERATORS - UNION, UNION ALL, EXCEPT, INTERSECT
-- UNION, UNION ALL, EXCEPT, INTERSECT

-- SET OPERATORS COMBINE THE RESULTS OF MULTIPLE QUERIES INTO A SINGLE RESULT SET
-- COMBINING ROWS (JOINS COMBINES COLUMNS)

										--RULES
--CLAUSES CAN BE USED ALMOST IN ALL CLAUSES
	-- ORDER BY IS ALLOWED ONLY ONCE AND ONLY AT THE END
									-- SELECT
										--FIRSTNAME
										--LASTNAME
									-- FROM CUSTOMERS
									--JOIN CLAUSE
									--WHERE CLAUSE
									--GROUP BY CLAUSE
									--UNION
									--SELECT
										--FIRSTNAME
										--LASTNAME
									-- FROM EMPLOYEES
									--JOIN CLAUSE
									--WHERE CLAUSE
									--GROUP BY CLAUSE
									--ORDER BY FIRSTNAME -> USED AT THE END 

--NUMBER OF COLUMNS
	-- THE NUMBER OF COLUMNS IN EACH QUERY MUST BE THE SAME

-- DATA TYPES
	-- DATA TYPES OF COLUMNS IN EACH QUERY MUST BE COMPATIBLE 

-- ORDER OF COLUMNS
 -- THE ORDER OF THE COLUMNS IN EACG QUERY MUST BE THE SAME

 -- COLUMN ALIASES
	-- THE COLUMNS NAME IN THE RESULT SET ARE DETERMINED BY THE COLUMN NAME SPECIFIED IN THE FIRST QUERY
		-- FIRST COLUMN DETERMINS COLUMN NAMES

--CORRECT COLUMNS
	-- EVEN IF ALL RULES ARE MET AND SQL SHOWS NO ERRORS, THE RESULTS MAY BE INCORRECT
	-- INCORRECT COLUMN SELECTION LEADS TO INACCURATE RESULTS




-- UNION
-- RETURNS ALL DISTINCT ROWS FROM BOTH QUERIES
	-- REMOVES ALL DUPLICATES
--COMBINE THE DATA FROM EMPLOYEES AND CUSTOMERS INTO ONE TABLE
SELECT 
EmployeeID AS ID,
FirstName AS FIRST_NAME,
LastName AS LAST_NAME
FROM SALES.Employees

	UNION

SELECT 
CustomerID,
FirstName,
LastName
FROM SALES.Customers

-- UNION ALL
-- RETURNS ALL ROWS FROM BOTH QUERIES, INCLUDING DUPLICATES

--COMBINE THE DATA FROM EMPLOYEES AND CUSTOMERS INTO ONE TABLE, INCLUDING DUPLICATES

SELECT 
EmployeeID AS ID,
FirstName AS FIRST_NAME,
LastName AS LAST_NAME
FROM SALES.Employees

	UNION ALL

SELECT 
CustomerID,
FirstName,
LastName
FROM SALES.Customers


-- EXCEPT
-- RETURNS ALL DISTINCT ROWS FROM THE FIRST QUERY, THAT ARE NOT FOUDN IN THE SECOND QUERY 

-- RETURN ALL EMPLOYEES WHO ARE NOT CUSTOMERS
	-- ROWS IN THE EMPLOYEES SET THAT ARE NOT IN THE CUSTOMER SET
SELECT 
EmployeeID AS ID,
FirstName AS FIRST_NAME,
LastName AS LAST_NAME
FROM SALES.Employees

	EXCEPT

SELECT 
CustomerID,
FirstName,
LastName
FROM SALES.Customers


-- INTERSECT
-- RETURNS ROWS THAT ARE COMMON IN BOTH QUERIES, REMOVES DUPLICATES

-- FIND THE EMPLOYEES WHO ARE ALSO CUSTOMERS

SELECT
EmployeeID AS ID,
FirstName AS FIRST_NAME,
LastName AS LAST_NAME
FROM SALES.Employees

INTERSECT

SELECT 
CustomerID,
FirstName,
LastName
FROM SALES.Customers


-- PRACTICE
-- ORDERS ARE STORED IN SEPERATE TABLES ( ORDERS & ORDERESARCHIVE)
-- COMBINE ALL ORDERS INTO ONE REPORT WITHOUT DUPLICATES

SELECT
'ORDERS' AS SOURCETABLE,
[OrderID]
      ,[ProductID]
      ,[CustomerID]
      ,[SalesPersonID]
      ,[OrderDate]
      ,[ShipDate]
      ,[OrderStatus]
      ,[ShipAddress]
      ,[BillAddress]
      ,[Quantity]
      ,[Sales]
      ,[CreationTime]
FROM SALES.Orders

UNION

SELECT 
'ORDERSARCHIVE' AS SOURCETABLE,

[OrderID]
      ,[ProductID]
      ,[CustomerID]
      ,[SalesPersonID]
      ,[OrderDate]
      ,[ShipDate]
      ,[OrderStatus]
      ,[ShipAddress]
      ,[BillAddress]
      ,[Quantity]
      ,[Sales]
      ,[CreationTime]
FROM SALES.OrdersArchive

-- DELTA DETECION
-- IDENTIFYING THE DIFFERENCES OR CHANGES (DELTA) BETWEEN TWO BATCHES OF DATA

-- DATA COMPLETENESS CHECK
-- EXCEPT OPERATOR CAN BE USED TO COMPARE TABLES TO DETECT DISCREPANCIES BETWEEN DATABASES
	-- USED IN DATA MITGRATION 


