-- SINGLE ROW FUNCTIONS

-- STRING FUNCTIONS
	-- MANIPULATION
		-- CONCAT, UPPER, LOWER, TRIM, REPLACE
	-- CALCULATION
		--LEN
	--STRING EXTRACTION
		--LEFT, RIGHT, SUBSTRING

--MANIPULATION
--CONCAT
	-- COMBINE MULITPLE STRING VALUES INTO ONE VALUE
-- SHOW A LIST OF CUSTOMERS FIRST NAME AND THEIR COUNTRY IN ONE COLUMN
SELECT 
CONCAT(first_name,', ', COUNTRY) AS 'CUSTOMER & COUNTRY'
FROM customers



--UPPER & LOWER
	-- CONVERT TO UPPER CASE OR LOWER
-- CONVERT THE CUSTOMER FRIST NAME TO LOWER CASE
SELECT 
LOWER(FIRST_NAME)
FROM customers

-- CONVERT THE CUSTOMER FRIST NAME TO UPPER CASE
SELECT 
UPPER(FIRST_NAME)
FROM customers



--TRIM
 -- REMOVES LEADING AND TRAILING SPACES
 -- FIND CUSTOMERS WHOSE FIRST NAME CONTAINS LEADING OR TRAILING SPACES
 
 SELECT
 FIRST_NAME
 FROM customers
 WHERE FIRST_NAME != TRIM(first_name)

 --
 SELECT
 TRIM(FIRST_NAME)
 FROM customers


 -- REPLACE
	-- REPLACES SPECIFIC CHARACTER WITH A NEW CHARACTER 
-- REMOVE DASHES FROM A PHONE NUMBER
SELECT 
'123-345-567' AS PHONE,
REPLACE('123-345-567', '-','') AS CORRECTED_PHONE

-- REPLACE FILE EXTENCE FROM TXT TO CSV
SELECT
'REPORT.TXT' AS OLD_FILE_NAME,
REPLACE('REPORT.TXT','.TXT','.CSV') AS NEW_FILE_NAME


-- CALCULATION
--LEN
	-- COUNTS HOW MANY CHARACTERS IN A VALUE
SELECT
FIRST_NAME,
LEN(FIRST_NAME) AS LENGTH_OF_NAME
FROM customers


-- STRING EXTRACTION
-- LEFT & RIGHT
	-- LEFT: EXTRACTS SPECIFIC NUMBER OF CHARACTERS FROM THE START
	-- RIGHT: EXTRACTS SPECIFIC NUMBER OF CHARACTERS FROM THE END
-- EXTRACT THE FIRST TWO CHARACTERS AND THE LAST TWO FROM THE CUSTOMERS FIRST NAME
SELECT
FIRST_NAME,
LEFT(TRIM(FIRST_NAME),2) AS 'FIRST2',
RIGHT(TRIM(FIRST_NAME),2) AS 'LAST2'
FROM customers

-- SUBSTRING
	-- EXTRACT A PART OF A STRING FROM A DEFINED STARTING POSITION
-- AFTER THE SECOND HARACTER, EXTRACT THE NEXT TWO
SELECT
first_name,
SUBSTRING(TRIM(FIRST_NAME), 3,2)
FROM customers

--EXTRA ALL AFTER THE SECOND CHARACTER
SELECT
FIRST_NAME,
SUBSTRING(TRIM(first_name),3, LEN(FIRST_NAME))
FROM customers