-- WHERE CONDITIONS 
	-- COMPARISON OPERATORS (=,<> =!, >,>=,<,<=)
	-- lOGICAL OPERATORS (AND, OR, NOT)
	-- RANGE OPERATORS (BETWEEN)
	-- MEMBERSHIP OPERATORS (IN, NOT IN)
	-- SEARCH OPERATOR (LIKE)



--COMPARISON (=,<> !=, >,>=,<,<=)
	-- expresion OPERATOR expresion
	-- COLUMN 1 = COLUMN 2
	-- COLUMN 1 = VALUE
	-- FUNCTION = VALUE
	-- EXPRESION = VALUE 
	-- SUBQUERY = VALUE

-- RETRIVE CUSTOMERS WHERE COUNTRY IS USA
SELECT * 
FROM DBO.customers
WHERE country = 'USA'

-- RETRIVE CUSTOMERS WHERE COUNTRY IS GERMANY
SELECT * 
FROM DBO.customers
WHERE country = 'GERMANY'

-- RETRIVE CUSTOMERS WHERE COUNTRY IS NOT GERMANY
SELECT * 
FROM DBO.customers
WHERE country != 'GERMANY'

-- RETRIEVE CUSTOMERS WITH A SCORE GREATER THAN 500
SELECT * 
FROM DBO.customers
WHERE SCORE > 500

-- RETRIEVE CUSTOMERS WITH A SCORE OF 500 OR MORE
SELECT * 
FROM DBO.customers
WHERE SCORE >= 500

-- RETRIEVE CUSTOMERS WITH A SCORE LESS THAN 500
SELECT * 
FROM DBO.customers
WHERE SCORE < 500

-- RETRIEVE CUSTOMERS WITH A SCORE OF 500 OR LESS
SELECT * 
FROM DBO.customers
WHERE SCORE <= 500



-- lOGICAL OPERATORS (AND, OR, NOT)
-- AND -> ALL CONDITIONS MUST BE TRUE

-- SELECT ALL CUSTOMERS FROM USA THAT HAVE A SCORE ABOVE 500
SELECT *
FROM DBO.customers
WHERE country = 'USA' AND SCORE > 500 

-- OR -> ONE OF THE CODITIONS HAVE TO BE TRUE
-- SELECT ALL CUSTOMERS FROM USE OR HAVE A SCORE ABOVE 500
SELECT *
FROM DBO.customers
WHERE country = 'USA' OR SCORE > 500

-- NOT -> WHERE THE CONDITON DOES NOT APPLY
SELECT *
FROM DBO.customers
WHERE not country = 'USA' AND SCORE > 500


-- RANGE OPERATOR
--BETWEEN -> CHECK IF A VALUE FALLS WITHIN A RANGE

--RETRIEVE ALL CUSTOMERS WITH A SCORE BETWEEN 100 AND 500
SELECT * 
FROM DBO.customers
WHERE SCORE BETWEEN 100 AND 500


--MEMBERSHIP OPERATOR
--IN -> CHECK IF VALUES ARE A MEMBER OF A LIST
--NOT IN -> CHECK IF VALUES ARE NOT A MEMBER OF A LIST

-- RETRIVE ALL CUSTOMERS FROM GERMANY OR USA
SELECT * 
FROM DBO.customers
WHERE COUNTRY IN ('GERMANY','USA')



-- SEARCH OPERATOR
-- LIKE -> SEARCH FOR A PATTERN IN TEXT
	-- % -> ANYTHING 
	-- _ -> EXACT 

-- RETRIEVE ALL CUSTOMERS THAT NAME STARTS WITH A 'M'
SELECT * 
FROM DBO.customers
WHERE first_name LIKE 'M%'

-- RETRIEVE ALL CUSTOMERS THAT FIRST NAME ENDS WITH 'N'
SELECT *
FROM DBO.customers
WHERE first_name LIKE '%N'

-- RETRIEVE ALL CUSTOMERS THAT FIRST NAME CONTAINS A 'R'
SELECT *
FROM DBO.customers
WHERE first_name LIKE '%R%'

-- RETRIEVE ALL CUSTOMERS THAT FIRST NAME CONTAINS A 'R' IN THE THIRD POSITION
SELECT *
FROM DBO.customers
WHERE FIRST_NAME LIKE '__R%'

