/* BE AWARE OF THE '*  /' THAT MAKE THE CODE INTO NOTES
-- CTE COMMON TABLE EXPRESSIONS
	-- TEMPORARY NAMED RESULT SET (VIRTUAL TABLE) THAT CAN BE USED MULTIPLE TIMES WITHIN YOUR QUERY
	-- TO SIMPLIFY AND ORGANIZE COMPLEX QUERY

-- NONE-RECURSIVE CTE
	-- STANDALONE CTE
		-- DEFINED AND USED INDEPENDENTLY. RUNS INDEPENDENTLY AS ITS SELF-CONCETAINED AND DOESNT RELY ON OTHER CTES OR QUERIES
	-- SYNTAX
		/* WITH CTE-NAME AS 
		(
			SELECT...
			FROM...
			WHERE...
		)
		TO USE IT IN ANOTHER QUERY:
		SELECT...
		FROM CTE-NAME
		WHERE...
		*/


 --EXAMPLE
 -- STEP 1: FIND THE TOTAL SALES PER CUSTOMER
	-- FIRST WRITE THE QUEREY 
	-- THEN NAME IT INTO A CTE
WITH CTE_TOTAL_SALES AS
(
 SELECT
	 CustomerID,
	 SUM(SALES) AS TOTAL_SALES
 FROM SALES.ORDERS
 GROUP BY CustomerID
)
--STEP 2: JOIN THE CTE INTO THE MAIN QUERY 
-- MAIN QUEREY
SELECT
c.CustomerID,
c.FirstName,
c.LastName,
cts.TOTAL_SALES
FROM SALES.Customers c
LEFT JOIN CTE_TOTAL_SALES cts --> JOINING THE CTE INTO THE MAIN QUERY 
ON cts.CustomerID = c.CustomerID
ORDER BY CustomerID


-- MULTIPLE CTE'S
-- SYNTAX
		/* WITH CTE-NAME AS 
		(
			SELECT...
			FROM...
			WHERE...
		)
		, CTE-NAME2 AS
		(
			SELECT...
			FROM...
			WHERE...
		)
		, ETC.
		TO USE IT IN ANOTHER QUERY:
		SELECT...
		FROM CTE-NAME
		JOIN CTE-NAME2
		WHERE...
		*/


--EXAMPLE
--1. FIND THE TOTAL SALES PER CUSTOMER
--2. FIND THE LAST ORDER DATE PER CUSTOMER

WITH CTE_TOTAL_SALES AS
(
 SELECT
	 CustomerID,
	 SUM(SALES) AS TOTAL_SALES
 FROM SALES.ORDERS
 GROUP BY CustomerID
)
, CTE_RECENT_ORDER AS
(
SELECT
CUSTOMERID,
CAST(MAX(CreationTime) AS DATE) AS RECENT_ORDER,
MAX(CreationTime) AS RECENT_ORDER_datetime
FROM SALES.Orders
GROUP BY CustomerID
)

--STEP 2: JOIN THE CTE INTO THE MAIN QUERY 
-- MAIN QUEREY
SELECT
c.CustomerID,
c.FirstName,
c.LastName,
cts.TOTAL_SALES,
cro.RECENT_ORDER
FROM SALES.Customers c
LEFT JOIN CTE_TOTAL_SALES cts --> JOINING THE CTE INTO THE MAIN QUERY 
ON cts.CustomerID = c.CustomerID
LEFT JOIN CTE_RECENT_ORDER cro --> JOINING THE CTE INTO THE MAIN QUER
ON cro.CUSTOMERID = c.CustomerID
ORDER BY CustomerID

*/
	-- NESTED CTE
		-- CTE INSIDE ANOTHER CTE
		-- A NESTED CTE USES THE RESULT OF ANOTHER CTE, SO IT CANT RUN INDEPENDENTLY

		-- SYNTAX
		/* WITH CTE-NAME AS 
		(
			SELECT...
			FROM...
			WHERE...
		)
		, CTE-NAME2 AS
		(
			SELECT...
			FROM CTE-NAME  ---> DEPENDENT ON CTE-1
			WHERE...
		)
		, ETC.
		TO USE IT IN ANOTHER QUERY:
		SELECT...
		FROM CTE-NAME2
		WHERE...
		*/
--EXAMPLE
--1. FIND THE TOTAL SALES PER CUSTOMER
--2. FIND THE LAST ORDER DATE PER CUSTOMER
--3. RANK CUSTOMERS BASED ON TOTAL SALES PER CUSTOMER

/*
WITH CTE_TOTAL_SALES AS
(
 SELECT
	 CustomerID,
	 SUM(SALES) AS TOTAL_SALES
 FROM SALES.ORDERS
 GROUP BY CustomerID
)
, CTE_RECENT_ORDER AS
(
SELECT
CUSTOMERID,
CAST(MAX(CreationTime) AS DATE) AS RECENT_ORDER,
MAX(CreationTime) AS RECENT_ORDER_datetime
FROM SALES.Orders
GROUP BY CustomerID
)
, CTE_RANK AS
( SELECT
CustomerID,
TOTAL_SALES,
RANK() OVER (ORDER BY TOTAL_SALES DESC) AS RANK
FROM CTE_TOTAL_SALES --> NESTING THE CTE
)

--STEP 2: JOIN THE CTE INTO THE MAIN QUERY 
-- MAIN QUEREY
SELECT
c.CustomerID,
c.FirstName,
c.LastName,
cts.TOTAL_SALES,
cro.RECENT_ORDER,
cr.RANK
FROM SALES.Customers c
LEFT JOIN CTE_TOTAL_SALES cts --> JOINING THE CTE INTO THE MAIN QUERY 
ON cts.CustomerID = c.CustomerID
LEFT JOIN CTE_RECENT_ORDER cro --> JOINING THE CTE INTO THE MAIN QUER
ON cro.CUSTOMERID = c.CustomerID
LEFT JOIN CTE_RANK cr
ON cr.TOTAL_SALES = cts.TOTAL_SALES
ORDER BY CustomerID
*/
--EXAMPLE
--1. FIND THE TOTAL SALES PER CUSTOMER
--2. FIND THE LAST ORDER DATE PER CUSTOMER
--3. RANK CUSTOMERS BASED ON TOTAL SALES PER CUSTOMER
--4. SEGMENT CUSTOMERS BASED ON THEIR TOTAL SALES
/*
WITH CTE_TOTAL_SALES AS
(
 SELECT
	 CustomerID,
	 SUM(SALES) AS TOTAL_SALES
 FROM SALES.ORDERS
 GROUP BY CustomerID
)
, CTE_RECENT_ORDER AS
(
SELECT
CUSTOMERID,
CAST(MAX(CreationTime) AS DATE) AS RECENT_ORDER,
MAX(CreationTime) AS RECENT_ORDER_datetime
FROM SALES.Orders
GROUP BY CustomerID
)
, CTE_RANK AS
( SELECT
CustomerID,
TOTAL_SALES,
RANK() OVER (ORDER BY TOTAL_SALES DESC) AS RANK
FROM CTE_TOTAL_SALES --> NESTING THE CTE
)
, CTE_SALES_CATEGORY AS
( SELECT
CUSTOMERID,
CASE  
	WHEN TOTAL_SALES < 60 THEN 'LOW'
	WHEN TOTAL_SALES BETWEEN 61 AND 90 THEN 'MEDIUM'
	WHEN TOTAL_SALES > 90 THEN 'HIGH'
END AS CATEGORY
FROM CTE_TOTAL_SALES
)

--STEP 2: JOIN THE CTE INTO THE MAIN QUERY 
-- MAIN QUEREY
SELECT
c.CustomerID,
c.FirstName,
c.LastName,
cts.TOTAL_SALES,
cro.RECENT_ORDER,
cr.RANK,
cc.CATEGORY
FROM SALES.Customers c
LEFT JOIN CTE_TOTAL_SALES cts --> JOINING THE CTE INTO THE MAIN QUERY 
ON cts.CustomerID = c.CustomerID
LEFT JOIN CTE_RECENT_ORDER cro --> JOINING THE CTE INTO THE MAIN QUER
ON cro.CUSTOMERID = c.CustomerID
LEFT JOIN CTE_RANK cr
ON cr.TOTAL_SALES = cts.TOTAL_SALES
LEFT JOIN CTE_SALES_CATEGORY cc
ON c.CustomerID = cc.CustomerID
ORDER BY CustomerID
*/

-- RECURSIVE CTE
-- SELF-REFERENCING QUERY THAT REPEATEDLY PROCESSES DATA UNTILL A SPECIFIC CONDITION IS MET

-- SYNTAX
/*		WITH CTE-NAME AS 
		(
			SELECT...
			FROM...
			WHERE...
			UNION ALL
			SELECT...
			FROM CTE-NAME
			WHERE [BREAK CONDITION]
		)
		SELECT ...
		FROM CTE-NAME
		WHERE...

/*
-- EXAMPLE
-- GENERATE A SEQUENCE OF NUMBERS FROM 1 TO 20
*/
WITH SERIES AS
( SELECT
1 AS NUMBER
UNION ALL
SELECT
NUMBER + 1
FROM SERIES
WHERE NUMBER < 20 
)


SELECT 
*
FROM SERIES
--OPTION (MAXRECURSION 1000) ---> LIMITS THE RECURSION
*/
-- EXAMPLES
-- SHOW THE EMPLOYEE HIERARCHY BY DISPLAYING EACH EMPLOYEES LEVEL WITHIN THE ORGANIZATION
WITH HIERARCHY AS
(
SELECT 
EmployeeID,
FirstName,
ManagerID,
1 AS LEVEL
FROM Sales.Employees
WHERE ManagerID IS NULL

UNION ALL

SELECT
e.EmployeeID,
e.FirstName,
e.ManagerID,
LEVEL + 1
FROM SALES.Employees AS e
INNER JOIN HIERARCHY
ON e.ManagerID = HIERARCHY.EmployeeID
)

SELECT
*
FROM HIERARCHY
