-- NULL FUNCTIONS
-- A NULL IS THE ABSENCE OF DATA, NOTHING, UNKNOWN

--ISNULL
--REPLACE A NULL WITH A SPECIFIED VALUE
SELECT 
ShipAddress
BillAddress,
ISNULL(ShipAddress, 'UNKNOWN') SHIPADDRESS_WITH_UNKNOWN, -- CONVERT UNKNOWNS TO 'UNKNOWN'
ISNULL(SHIPADDRESS, BillAddress) AS SHIP_TO_BILLING_IF_SHIP_TO_NOT_PROVIDED,-- CONVERTS THE NULLS TO THE BILLING ADDRESS
ISNULL(SHIPADDRESS, ISNULL(BILLADDRESS, 'CONFIRM WITH CUSTOMER')) AS CLEAN_SHIPPING_ADDRESS -- SINCE THERE ARE NULLS IN BILLING, JUST TO HAVE A FLAG VALUE
FROM SALES.ORDERS

-- COALESCE
--RETURNS THE FIRST NON-NULL VALUE FROM A LIST

SELECT
BILLADDRESS,
SHIPADDRESS,
COALESCE(SHIPADDRESS, BILLADDRESS, 'CALL CUSTOMER') AS CLEANED_SHIPPING_ADDRESS -- A CLEANER VERSION OF THE CLEAN_SHIPPING_ADDRESS ABOVE
FROM SALES.Orders

--- FIND AVG SCORE FOR THE CUSTOMERS
SELECT 
SUM(ISNULL(SCORE,0))/COUNT(*) AS AVG_SCORE
FROM SALES.customers

-- DISPLAY THE FULL NAME OF CUSTOMERS IN A SINGLE FIELD
-- BY MERGING THEIR FIRST AND LAST NAME
-- ANND ADD 10 BONUS POINTS TO EACH CUSTOMERS SCORE

SELECT 
CUSTOMERID,
COALESCE(FirstName,'') + ' ' + COALESCE(LastName, '') AS CUSTOMER_NAME,
COALESCE(SCORE,'') + 10 AS NEW_SCORE
FROM SALES.Customers

-- SORT THE CUSTOMERS FROM THE LOWEST TO THE HIGHEST SCORE, WITH NULLS APPEARING LAST
SELECT 
CUSTOMERID,
SCORE
FROM SALES.Customers
ORDER BY CASE WHEN SCORE IS NULL THEN 1 ELSE 0 END ASC


-- NULLIF
-- REPLACE A VALUE WITH A NULL

-- FIND THE SALES PRICE FOR EACH ORDER BY DIVIDING THE SALES BY THE QUANTITY 
SELECT 
ORDERID,
SALES,
Quantity,
SALES/NULLIF(QUANTITY,0) AS PRICE
FROM SALES.ORDERS


-- IS NULL
--RETURNS TRUE IF VALUE IS NULL
--IS NOT NULL 
-- TRUE IF VALUE IS NOT NULL


-- RETRIEVE ALL CUSTOMERS WHERE THE SCORE IS NULL
SELECT
CustomerID,
SCORE
FROM SALES.Customers
WHERE SCORE IS NULL

-- RETRIEVE ALL CUSTOMERS WHO HAVE A SCORE
SELECT
CustomerID,
SCORE
FROM SALES.Customers
WHERE SCORE IS NOT NULL



-- LIST ALL DETAILS FOR CUSTOMERS WHO HAVE NOT PLACED ANY ORDERS
SELECT *
FROM SALES.Customers 
LEFT JOIN SALES.Orders
ON SALES.Customers.CustomerID = SALES.ORDERS.CustomerID
WHERE SALES.Orders.OrderID IS NULL