--WINDOW FUNCTIONS
-- FUCTIONS THAT PERFORM CALCULATIONS ON A SPECIFIC SUBSET OF DATA WITHOUT LOSING THE LEVEL OF DETAILS OF ROWS

--FIND THE TOTAL SALES ACROSS ALL ORDERS
SELECT
SUM(SALES)
FROM SALES.Orders;
SELECT 
ORDERID,
SALES,
SUM(SALES) OVER () AS TOTAL_SALES
FROM SALES.ORDERS

-- FIND THE TOTAL SALES FOR EACH PRODUCT
SELECT
PRODUCTID,
SUM(SALES) AS TOTAL_SALES
FROM SALES.Orders
GROUP BY ProductID

-- FIND THE TOTAL SALES FOR EACH PRODUCT (INCLUDE ORDER ID AND ORDERDATE)
SELECT
	ORDERID,
	ORDERDATE,
	PRODUCTID,
	SUM(SALES) OVER (PARTITION BY PRODUCTID) AS TOTAL_SALES
FROM SALES.Orders

-- FIND THE TOTAL SALES AND SALES PER ORDER, FOR EACH PRODUCT
SELECT
	ORDERID,
	PRODUCTID,
	SALES AS ORDER_SALES,
	SUM(SALES) OVER (PARTITION BY PRODUCTID) AS TOTA_PRODUCT_SALES
FROM SALES.Orders
--

-- sum of sales per month by product
select distinct
datename(month,orderdate) as month,
productid,
sum(sales) over (partition by month(orderdate), productid) as Total_sales_per_month
from sales.Orders

--

-- FIND THE TOTAL SALES ACROSS ALL ORDERS, ADDITIONALL PROVIDE DETAILS SUCH AS ORDER ID AND ORDER DATE
SELECT
ORDERID,
ORDERDATE,
SUM(SALES) OVER ( ) AS TOTAL_SALES
FROM SALES.Orders

-- FIND THE TOTAL SALES ACROSS ALL ORDERS FOR EACH PRODUCT, ADDITIONALL PROVIDE DETAILS SUCH AS ORDER ID AND ORDER DATE (1)
-- ADD IN TOTAL SALES FOR ALL ORDERS (2)
-- ADD IN BY ORDER STATUS (3)
SELECT
ORDERID,
ORDERDATE,
PRODUCTID,
ORDERSTATUS,
SALES,
SUM(SALES) OVER () AS TOTAL_SALES_OF_ALL_ORDERS,-- (2)
SUM(SALES) OVER (PARTITION BY PRODUCTID ) AS TOTAL_SALES_BY_PRODUCT,-- (1)
SUM(SALES) OVER (PARTITION BY PRODUCTID, ORDERSTATUS ) AS TOTAL_SALES_BY_PRODUCT_AND_ORDERSTATUS -- (3)
FROM SALES.Orders

--

--RANK EACH ORDER BASED ON THEIR SALES FROM HIGHEST TO THE LOWEST, ADDITIONALLY PROVIDE DETAILS SUCH AS ORDER ID AND ORDER DATE
SELECT
ORDERID,
ORDERDATE,
SALES,
RANK() OVER (ORDER BY SALES DESC) AS RANK 
FROM SALES.Orders

-- WINDOW FRAME
--DEFINES A SUBSET OF ROWS WITHIN EACH WINDOW THAT IS RELEVANT FOR THE CALCULATION
SELECT
ORDERID,
ORDERDATE,
ORDERSTATUS,
SALES,
SUM(SALES) OVER (PARTITION BY ORDERSTATUS ORDER BY ORDERDATE ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING ) AS TOTAL_SALES
FROM SALES.Orders

-- FIND THE TOTAL SALES FOR EACH ORDER STATUS, BUT ONLY FOR PRODUCTS 101 AND 102
SELECT
DISTINCT
ProductID,
ORDERSTATUS,
SUM(SALES) OVER (PARTITION BY PRODUCTID, ORDERSTATUS) AS TOTAL_SALES
FROM SALES.ORDERS
WHERE PRODUCTID = '101' OR PRODUCTID =  '102'

-- RANK CUSTOMERS BASED ON THEIR TOTAL SALES
SELECT 
CUSTOMERID,
SUM(SALES) AS TOTAL_SALES,
RANK () OVER (ORDER BY SUM(SALES) DESC) AS CUSTOMER_RANK
FROM SALES.Orders
GROUP BY CustomerID


-- WINDOW AGGREGATE FUNCTIONS
-- COUNT
SELECT DISTINCT
ProductID,
COUNT(Sales) OVER (PARTITION BY PRODUCTID) AS NUM_OF_ORDERS
FROM SALES.ORDERS
-- FIND THE TOTAL NUMBER OF ORDERS
SELECT
CUSTOMERID,
ORDERID,
ORDERDATE,
COUNT(*) OVER () AS TOTAL_ORDERS,
COUNT(*) OVER (PARTITION BY CUSTOMERID) TOTAL_ORDERS_BY_CUSTOMER
FROM SALES.ORDERS
-- FIND THE TOTAL NUMBER OF CUSTOMERS
SELECT
COUNT(*) OVER () AS CUSTOMER_COUNT,
*,
COUNT(SCORE) OVER () AS SCORE_COUNT
FROM SALES.Customers

-- SUM
-- FIND THE TOTAL SALES ACROSS ALL ORDERS, TOTAL SALES PER PRODUCT, INCLUDE ORDER ID AND ORDER DATE
SELECT
ORDERID,
ORDERDATE,
PRODUCTID,
SUM(SALES) OVER () AS TOTAL_SALES,
SUM(SALES) OVER (PARTITION BY PRODUCTID) AS SUM_PRODUCT_SALES
FROM SALES.ORDERS
ORDER BY ProductID ASC
-- FIND THE PERCENTAGE CONTROBUTION OF EACH PRODUCT SALES TO THE TOTAL SALES
SELECT DISTINCT
PRODUCTID,
SUM(SALES) OVER () AS TOTAL_SALES,
SUM(SALES) OVER (PARTITION BY PRODUCTID) AS PRODUCT_SALES,
(SUM(CAST(SALES AS FLOAT)) OVER (PARTITION BY PRODUCTID) / SUM(SALES) OVER ())*100  AS CONTRIBUTION
FROM SALES.ORDERS


--AVERAGE
SELECT DISTINCT
PRODUCTID,
COUNT(*) OVER (PARTITION BY PRODUCTID) AS NUMBER_OF_ORDERS,
AVG(COALESCE(SALES,0)) OVER (PARTITION BY PRODUCTID) AS AVG_PRODUCT_SALES -- USE COALESCE TO HANDLE ANY NULL VALUES AND CONVERT THEM TO 0
FROM SALES.ORDERS

-- FIND AVG SALES ACROSS ALL ORDER, FOR EACH PRODUCT, INCLUDE ORDER ID NA DORDER DATE
SELECT
ORDERID,
ORDERDATE,
PRODUCTID,
AVG(SALES) OVER () AS AVG_ORDERS,
AVG(SALES) OVER (PARTITION BY PRODUCTID) AS AVG_SALES_PRODUCT
FROM SALES.ORDERS

-- FIND THE AVERAGE SCORE OF CUSTOMERS, INCLUDE CUSTOMER ID AND LASTNAME
SELECT
CUSTOMERID,
LASTNAME,
AVG(COALESCE(SCORE,0)) OVER () AS AVG_SCORE
FROM SALES.Customers

-- FIND ALL ORDERS WHERE SALES ARE HIGHER THAN THE AVERAGE SALES ACROSS ALL ORDERS
SELECT
ORDERID,
SALES,
AVG_SALES
FROM (
	SELECT 
	*,
	AVG(SALES) OVER () AS AVG_SALES
	FROM SALES.Orders
)t
WHERE SALES > AVG_SALES

-- MIN AND MAX
-- FIND THE HIGHEST AND LOWEST SALES ACROSS ALL ORDERS, AND FOR EACH PRODUCT, PROVIDE ORDER ID AND ORDER DATE
SELECT
ORDERID,
ORDERDATE,
PRODUCTID,
MAX(SALES) OVER () AS MAX_SALES,
MIN(COALESCE(SALES,0)) OVER () AS MIN_SALES,
MAX(SALES) OVER (PARTITION BY PRODUCTID) AS MAX_PRODUCT_SALES,
MIN(COALESCE(SALES,0)) OVER (PARTITION BY PRODUCTID) AS MIN_PRODUCT_SALES
FROM SALES.Orders

-- CALCULATE THE DEVIATION OF EACG SALE FROM BOTH THE MIN AND MAX SALES AMOUNT
SELECT
*,
SALES - MIN_SALES AS LOWER_DEVIATION,
MAX_SALES - SALES AS UPPER_DEVIATION
FROM(
	SELECT
	*,
	MIN(SALES) OVER () AS MIN_SALES,
	MAX(SALES) OVER () AS MAX_SALES
	FROM SALES.Orders
)t

-- RUNNING AND ROLLING TOTALS 
-- TRACKING CURRENT SALES WITH TARGET SALES
-- PROVIODING INSIGHTS INTO HISTORICAL PATTERNS
-- RUNNING TOTAL - AGGREAGETE ALL VALYES FROM THE BEGINING UP TO THE CURRENT POINT
-- ROLLING TOTAL - AGGREGATE ALL VALUES WITHIN A FIXED WINDOW (30DAYS). AS NEW DATA IS ADDED, THE OLDEST POINT WILL BE DROPPED

-- CALCULATE THE MOVING AVERAGE OF SALES FOR EACH PRODUCT OVER TIME
SELECT 
ORDERDATE,
PRODUCTID,
SALES,
AVG(SALES) OVER (PARTITION BY PRODUCTID ORDER BY ORDERDATE) AS MOVING_SALES_AVG_PRODUCTID
FROM SALES.Orders
-- CALCULATE THE MOVING AVERAGE OF SALES FOR EACH PRODUCT OVER TIME, ONLY INCLUDING THE NEXT ORDER
SELECT 
ORDERDATE,
PRODUCTID,
SALES,
AVG(SALES) OVER (PARTITION BY PRODUCTID ORDER BY ORDERDATE ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) AS ROLLING_SALES_AVG_PRODUCTID
FROM SALES.Orders


-- RANKING FUNCTIONS
-- RANK () OVER ((OPTIONAL) PARTITION BY XYZ (REQUIRED) ORDER BY ZYX)

-- ROW_NUMBER() -> IGNORES TIES
--RANK THE ORDERS BASED ON THEIR SALES FROM THE HIGHEST TO LOWEST
SELECT
ORDERID,
SALES,
ROW_NUMBER() OVER (ORDER BY SALES DESC) AS RANK
FROM SALES.Orders

--RANK -> DOES NOT IGNORE TIES AND WILL LEAVE 'GAPS' IN RANK IF THERE ARE TIES
--RANK THE ORDERS BASED ON THEIR SALES FROM THE HIGHEST TO LOWEST
SELECT
ORDERID,
SALES,
RANK() OVER (ORDER BY SALES DESC) AS RANK
FROM SALES.Orders

--DENSE_RANK
-- SAME AS RANK, BUT WILL NOT LEAVE GAPS
--RANK THE ORDERS BASED ON THEIR SALES FROM THE HIGHEST TO LOWEST
SELECT
ORDERID,
SALES,
DENSE_RANK() OVER (ORDER BY SALES DESC) AS RANK
FROM SALES.Orders

--TOP-N ANALYSIS
-- SELECT THE TOP ORDER/SALE PER PRODUCT
select *
FROM(
	select
	productid,
	sales,
	orderid,
	row_number () over (partition by productid order by sales desc) as sales_rank
	from sales.orders
)t
WHERE SALES_RANK = 1

--BOTTOM-N ANALYSIS
--FIND THE LOWEST 2 CUSTOMERS BASED ON THEIR SALES
SELECT 
* 
FROM(
	SELECT 
	CUSTOMERID,
	SUM(SALES) AS TOTAL_SALES,
	ROW_NUMBER() OVER (ORDER BY SUM(SALES)) AS RANK
	FROM SALES.ORDERS
	GROUP BY CustomerID
)t
WHERE RANK <= 2

-- ASSIGN UNIQUE IDS TO THE ROWS OF THE 'ORDERS ARCHIVE' TABLE
SELECT 
ROW_NUMBER() OVER (ORDER BY ORDERID, ORDERDATE) AS PRIMARY_KEY,
* 
FROM SALES.OrdersArchive

-- IDENTIFY DUPLICATES
SELECT
* 
FROM (
		SELECT 
		ROW_NUMBER() OVER (PARTITION BY ORDERID ORDER BY CREATIONTIME DESC) AS PRIMARY_KEY,
		* 
		FROM SALES.OrdersArchive
)t
WHERE PRIMARY_KEY != 1

--NTILE()
--DIVIDES THE ROWS INTO A SPECIFIED NUMBER OF APPROXIMATELY EQUAL GROUPS (BUCKETS)
SELECT
ORDERID,
SALES,
NTILE(1) OVER (ORDER BY SALES DESC) AS ONEBUCKET,
NTILE(2) OVER (ORDER BY SALES DESC) AS TWOBUCKET,
NTILE(3) OVER (ORDER BY SALES DESC) AS TWOBUCKET
FROM SALES.Orders

-- SEGMENT ALL ORDERS INTO 3 CATEGORIES: HIGH MEDIUM ADN LOW
SELECT
OrderID,
SALES,
CASE FLAG
	WHEN 1 THEN 'HIGH'
	WHEN 2 THEN 'MEDIUM'
	ELSE 'LOW'
END AS SALES_CATEGORY
FROM(
	SELECT
	*,
	NTILE (3) OVER (ORDER BY SALES DESC) AS FLAG
	FROM SALES.Orders
)t

-- IN ORDER TO EXPORT THE DATA, DIVIDE THE ORDERS INTO 2 GROUPS
SELECT
*,
NTILE (2) OVER (ORDER BY ORDERID) AS GROUPS
FROM SALES.Orders

-- CUME_DIST
-- WILL USE THE LAST POSITION OF THE SHARED VALUE
SELECT
ORDERID,
SALES,
CUME_DIST() OVER (ORDER BY SALES DESC) AS RANKING
FROM SALES.Orders

-- PERCENT_RANK
-- WILL USE THE FIRST POSITION OF THE SHARED VALUE
SELECT
ORDERID,
SALES,
PERCENT_RANK() OVER (ORDER BY SALES DESC) AS RANKING
FROM SALES.Orders

-- FIND THE PRODUCTS THAT FALL WITHIN THE HIGHEST 40% OF PRICES
SELECT * FROM SALES.Products

SELECT 
*
FROM (
	SELECT 
	Product,
	PRICE,
	CUME_DIST() OVER (ORDER BY PRICE DESC) AS RANKING
	FROM SALES.Products
)t
WHERE RANKING <= .40

-- VALUE FUNCTIONS
-- LEAD (EXPRESSION, OFFSET (OPTIONAL, NUMBER OF ROWS FORARD OR BACKWARDS FROM CURRENT ROW), DEFAULT VALUE (IF THERES NO VALUE/NULL)) ACCESS A VALUE FROM THE NEXT ROW WITHIN A WINDOW 
-- LAG()  ACCESS A VALUE FROM THE PREVIOUS ROW WITHIN A WINDOW
SELECT 
PRODUCTID,
ORDERDATE,
SALES,
LEAD(SALES,2,0) OVER (PARTITION BY PRODUCTID ORDER BY ORDERDATE) AS TWO_FORWARD_BY_PRODUCT,
LEAD(SALES,2,0) OVER (ORDER BY ORDERDATE) AS TWO_FORWARD,
LAG(SALES,2,0) OVER (ORDER BY ORDERDATE) AS TWO_PREVIOUS,
LEAD(SALES) OVER (ORDER BY ORDERDATE) AS ONE_FORWARD,
LAG(SALES) OVER (ORDER BY ORDERDATE) AS ONE_PREVIOUS
FROM SALES.ORDERS

-- ANALYSE THE MONTH-OVER-MONTH PERFORMANCE BY FINDING THE PERCENTAGE CHANGE IN SALES BETWEEN THE CURRENT AND PREVIOUS MONTH 
		--MY ATTEMPT
SELECT
*,
CONCAT(((CAST(TOTAL_MONTH_SALES AS FLOAT) - PREVIOUS_MONTH_SALES)/PREVIOUS_MONTH_SALES) * 100,'%') AS PERCENT_CHANGE_MONTH_OVER_MONTH
FROM(
	SELECT 
	*,
	LAG(TOTAL_MONTH_SALES,1) OVER (ORDER BY ORDER_MONTH) AS PREVIOUS_MONTH_SALES
	FROM ( 
		SELECT DISTINCT
		MONTH(ORDERDATE) AS ORDER_MONTH,
		SUM(SALES) OVER (PARTITION BY MONTH(ORDERDATE) ORDER BY MONTH(ORDERDATE)) AS TOTAL_MONTH_SALES
		FROM SALES.Orders
	)t
)t


		-- EASIER AND CLEANER WAY
SELECT
*,
CONCAT((CAST(CURRENT_MONTH_SALES AS FLOAT) - PREVIOUS_MONTH_SALES) / PREVIOUS_MONTH_SALES * 100, '%') AS 'M-O-M_DELTA'
FROM (
	SELECT
	 MONTH(ORDERDATE) AS ORDER_MONTH,
	 SUM(SALES) AS CURRENT_MONTH_SALES,
	 LAG(SUM(SALES)) OVER (ORDER BY MONTH(ORDERDATE)) AS PREVIOUS_MONTH_SALES
	 FROM SALES.ORDERS
	 GROUP BY MONTH(ORDERDATE)
)t

--CUSTOMER RETENTION ANALYSIS
-- ANALYZE CUSTOMER LOYALTY BY RANKING CUSTOMERS BASED ON THE AVERAGE NUMBER OF DAYS BETWEEN ORDERS
SELECT
*,
ROW_NUMBER() OVER (ORDER BY COALESCE((AVG_DAYS_BETWEEN_ORDERS), 999999999 ) ASC) AS RANKING
FROM(
	SELECT DISTINCT 
	CUSTOMERID,
	AVG(-DAYS_BETWEEN_ORDERS) OVER (PARTITION BY CUSTOMERID) AS AVG_DAYS_BETWEEN_ORDERS
	FROM (
		SELECT
		CUSTOMERID,
		ORDERID,
		OrderDate,
		LAG(ORDERDATE) OVER (PARTITION BY CUSTOMERID ORDER BY ORDERDATE ASC) AS PREVIOUS_ORDER_DATE,
		DATEDIFF(DAY,ORDERDATE,LAG(ORDERDATE) OVER (PARTITION BY CUSTOMERID ORDER BY ORDERDATE ASC)) AS DAYS_BETWEEN_ORDERS
		FROM SALES.Orders
	)t
)t

-- FIRST_VALUE() 
	-- ACCESS A VALUE FROM THE FIRST ROW WITHIN A WINDOW
-- LAST_VALUE()
	-- ACCESS A VALUE FROM THE FIRST ROW WITHIN A WINDOW

-- FIND THE HIGHEST AND LOWEST SALES PER PRODUCT
SELECT DISTINCT
PRODUCTID,
COUNT(SALES) OVER (PARTITION BY PRODUCTID) AS NUMBER_OF_SALES,
FIRST_VALUE(Sales) OVER (PARTITION BY PRODUCTID ORDER BY SALES ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS LOWEST_SALE,
LAST_VALUE(SALES) OVER (PARTITION BY PRODUCTID ORDER BY SALES ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS HIGHEST_SALE
FROM SALES.Orders

-- NOW FIND THE DIFFERENCE BETWEEN THE CURRENT SALE AND THE LOWEST/ HIGHEST SALE
SELECT 
PRODUCTID,
COUNT(SALES) OVER (PARTITION BY PRODUCTID) AS NUMBER_OF_SALES,
SALES,
FIRST_VALUE(Sales) OVER (PARTITION BY PRODUCTID ORDER BY SALES ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS LOWEST_SALE,
LAST_VALUE(SALES) OVER (PARTITION BY PRODUCTID ORDER BY SALES ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS HIGHEST_SALE,
SALES - FIRST_VALUE(Sales) OVER (PARTITION BY PRODUCTID ORDER BY SALES ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS DIFF_FROM_LOWEST,
SALES - LAST_VALUE(SALES) OVER (PARTITION BY PRODUCTID ORDER BY SALES ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS DIFF_FROM_HIGHEST
FROM SALES.Orders