-- JOINS
-- INNER, LEFT, RIGHT, FULL


-- NO JOIN -> NOT A JOIN TYPE 
--VIEW RESULTS WITHOUT COMBINING TABLES
SELECT * FROM customers;
SELECT * FROM orders;


-- INNER JOIN 
-- RETURNS ONLY MATCHING ROWD FROM BOTH TABLES
-- OVERLAPING DATA
-- GET ALL CUSTOMERS ALONG WITH THEIR ORDERS BUT ONLY FOR CUSTOMERS WHO HAVE PLACED AN ORDER
SELECT 
CUSTOMERS.id,
customers.first_name,
ORDERS.order_id,
ORDERS.sales
FROM CUSTOMERS 
INNER JOIN orders
ON customers.ID = ORDERS.customer_id -- -> ORDER OF KEY DOES NOT MATTER IN INNER JOIN



-- LEFT JOIN
-- RETURNS ALL THE ROWS FROM THE LEFT TABLE AND THE MATCHING ROWS FROM THE RIGHT TABLE.
-- ALL ROWS FROM LEFT AND THE MATCHING DATA FROM THE RIGHT (ADDITIONAL DATA, NOT EVERYTHING)
	-- FROM (LEFT TABLE) -> WILL GIVE ALL RESULTS
	-- LEFT JOIN (RIGHT TABLE) 
-- GET ALL CUSTOMERS ALONG WITH THEIR ORDERS INCLUDING THOSE WITHOUT ORDERS
SELECT 
CUSTOMERS.id,
customers.first_name,
ORDERS.order_id,
ORDERS.sales
FROM customers
LEFT JOIN orders
ON CUSTOMERS.ID = ORDERS.customer_id



-- RIGHT JOIN
--ALL ROWS FROM THE RIGHT TABLE AND THE MATCHING DATA FROM THE LEFT (ADDITIONAL DATA, NOT EVERYTHING)
	-- FROM (LEFT TABLE) -> WILL GIVE MATCHING RESULTS
	-- RIGHT JOIN (RIGHT TABLE)
-- GET ALL CUSTOMERS ALONG WITH THEIR ORDERS, INCLUDING ORDERS WITHOUT MATCHING CUSTOMERS
SELECT
customers.ID,
CUSTOMERS.first_name,
ORDERS.order_id,
orders.sales
FROM customers
RIGHT JOIN orders
ON customers.id = orders.customer_id;


-- FULL JOIN
-- RETURNS ALL ROWS FROM BOTH TABLES
SELECT 
customers.ID,
CUSTOMERS.first_name,
ORDERS.order_id,
orders.sales
FROM customers
FULL JOIN orders
ON customers.id = orders.customer_id;



-- LEFT ANTI JOIN
	-- RETURNS ROWS FROM LEFT TABLE THAT HAS NO MATCH ON THE RIGHT TABLE
	-- ONLY EXIST IN LEFT TABLE
-- GET ALL CUSTOMERS WHO HAVENT PLACED AN ORDER
SELECT 
customers.ID,
CUSTOMERS.first_name,
ORDERS.order_id,
orders.sales
FROM customers
LEFT JOIN orders
ON customers.id = orders.customer_id
WHERE orders.customer_id IS NULL -- -> THIS IS THE ANTI PART OF THE LEFT ANTI JOIN


-- RIGHT ANTI JOIN
	-- RETURNS ROWS FROM RIGHT TABLE THAT HAS NO MATCH ON THE LEFT TABLE
	-- ONLY EXIST IN RIGHT TABLE

-- GET ALL ORDERS THAT DONT HAVE AN ASSOCIATED CUSTOMER
SELECT 
customers.ID,
CUSTOMERS.first_name,
ORDERS.order_id,
orders.sales
FROM customers
RIGHT JOIN orders
ON customers.id = orders.customer_id
WHERE customers.id IS NULL -- -> THIS IS THE ANTI PART OF THE RIGHT ANTI JOIN


-- FULL ANTI JOIN
-- RETURN THE ROWS THAT DONT MATCH ON EITHER TABLE

-- FIND CUSTOMERS WITH OUT ORDERS  AND ORDERS WITH OUT CUSTOMERS
SELECT 
customers.ID,
CUSTOMERS.first_name,
ORDERS.order_id,
orders.sales
FROM customers
FULL JOIN orders
ON customers.id = orders.customer_id
WHERE customers.id IS NULL OR orders.customer_id IS NULL -- -> THIS IS THE ANTI PART OF THE FULL ANTI JOIN


			-- PRACTICE
			-- GET ALL CUSTOMERS ALONG WITH THEIR ORDERS, BUT ONLY FOR CUSTOMERS WHO HAVE PLACED AN ORDER
			SELECT 
			*
			FROM customers
			LEFT JOIN orders
			ON customers.id = orders.customer_id
			WHERE orders.customer_id IS NOT NULL



-- CROSS JOIN
-- COMBINES EVERY ROW FROM THE LEFT AND THE RIGHT
-- ALL POSSIBLE COMBINATIONS
SELECT *
FROM customers
CROSS JOIN orders



--JOINING MULTIPLE TABLES
-- USING SALESDB, RETRIEVE A LIST OF ALL ORDERS, ALONG WITH THE RELATED CUSTOMER, PRODUCT, AND EMPLOYEE DETAILS

SELECT * FROM SALES.Orders
SELECT * FROM SALES.Customers
SELECT * FROM SALES.Products
SELECT * FROM SALES.Employees

SELECT 
SALES.Orders.OrderID AS ORDER_ID,
SALES.Customers.FirstName AS CUSTOMER_FIRSTNAME,
SALES.Customers.LastName AS CUSTOMER_LASTNAME,
SALES.Products.Product AS PRODUCT_NAME,
SALES.Orders.Sales AS SALES_AMOUNT,
SALES.Products.Price AS PRODUCT_PRICE,
SALES.Employees.FirstName AS EMPLOYEE_FIRSTNAME,
SALES.EMPLOYEES.LastName AS EMPLOYEE_LASTNAME
FROM SALES.Orders
	LEFT JOIN SALES.Customers
		ON Orders.CustomerID = Customers.CustomerID
	LEFT JOIN SALES.Products
		ON SALES.Orders.ProductID = SALES.Products.ProductID
	LEFT JOIN SALES.Employees
		ON SALES.Orders.SalesPersonID = SALES.Employees.EmployeeID

