-- DATE AND TIME

SELECT
ORDERID,
CREATIONTIME,
'2025-08-20' AS HARDCODED,
YEAR('2025-08-20') AS YEAR,
MONTH('2025-08-20') AS MONTH,
DAY('2025-08-20') AS DAY,
GETDATE() AS TODAY_TIMESTAMP
FROM SALES.Orders

-- FUNCTIONS
-- PART EXTRACTION
		--DAY
		--MONTH
		--YEAR
		--DATEPART
		--DATENAME
		--DATETRUNC
		--EOMONTH
--FORMAT & cASTING
		--FORMAT
		--CONVERT
		-- CAST
--CALCUALTIONS
		--DATEADD
		--DATEDIFF
--VALIDATION
		--ISDATE



--PART EXTRACTIONS
 -- DAY() - RETURNS DAY
 -- MONTH (0 - RETURNS MONTH
 -- YEAR() - RETURNS YEAR

 SELECT 
 GETDATE() AS FULL_DATE,
 DAY(GETDATE()) AS DAY,
 MONTH(GETDATE()) AS MONTH,
 YEAR(GETDATE()) AS YEAR,

 --DATEPART()
	--DATEPART(PART, DATE)
	 --PART
		--month, week, quarter

select 
datepart(year, CreationTime) YEAR,
datepart(week, CreationTime) WEEK,
datepart(month, CREATIONTIME) MONTH,
datepart(quarter, creationtime) QUARTER,
DATEPART(HOUR, CreationTime) HOUR,
DATEPART(MINUTE, CREATIONTIME) MINUTE,
DATEPART(SECOND, CREATIONTIME) SECOND
from sales.Orders


--DATENAME()
	-- RETURNS THE NAME OF THE DATEPART
SELECT 
DATENAME(MONTH, CreationTime) MONTH,
DATENAME(YEAR, CREATIONTIME) YEAR,
DATENAME(DAY, CREATIONTIME) DAY
FROM SALES.Orders


-- DATETRUNC()
 -- GIVVE THE DATETIME FOR A VALUE, BUT RESETS ALL VALUES AFTER THE DEFIND END POINT WILL BE 0
SELECT
DATETRUNC(HOUR, CREATIONTIME)
FROM SALES.Orders


--EOMONTH()
	-- RETURNS THE LAST DAY OF A MONTH

SELECT
ORDERID,
CREATIONTIME,
EOMONTH(CREATIONTIME) AS LASTDAYOFMONTH,
DAY(EOMONTH(CREATIONTIME)) AS LAST_DAY,
DAY(DATETRUNC(MONTH, CREATIONTIME)) AS FIRST_DAY,
CAST(DATETRUNC(MONTH, CREATIONTIME) AS DATE) AS STARTOFMONTH
FROM SALES.ORDERS


-- HOW MANY ORDERS WE PLACED EACH YEAR
SELECT
COUNT(*) AS NBROFORDERS,
YEAR(OrderDate) AS YEAR
FROM SALES.Orders
GROUP BY YEAR(OrderDate)

-- HOW MANY ORDERS PLACED PER MOMTH 
SELECT
DATENAME(MONTH,OrderDate) AS MONTH,
COUNT(*) AS NBR_OF_ORDER
FROM SALES.ORDERS
GROUP BY  DATENAME(MONTH,OrderDate)

-- SHOW ALL ORDERS PLACED DURING THE MONTH OF FEBURARY
SELECT 
DATENAME(MONTH, ORDERDATE) AS MONTH,
COUNT(*) AS NUM_OF_ORDERS
FROM SALES.ORDERS
WHERE (DATENAME(MONTH,ORDERDATE)) = 'FEBRUARY'
GROUP BY DATENAME(MONTH,ORDERDATE)



-- FORMATING AND CASTING
 -- CHANGING THE FORMAT FROM ONE TO ANOTHER
	--FORMAT(MM/DD/YY)
	-- CONVERT (6) 
-- CASTING
	-- CHANGE DATE TYPE
		-- STRING TO A NUMBER
		-- DATE TO STRING
		-- CAST() OR CONVERT()

-- FORMAT()
	-- FORMATES DATE AND TIME VALUE
	-- FORMAT(VALUE, FORMAT)
SELECT
FORMAT(CreationTime, 'MM/dd/yyyy'), -- case sensitve
FORMAT(CREATIONTIME, 'dd'),
fORMAT(CREATIONTIME, 'ddd'),
fORMAT(CREATIONTIME, 'dddd'),
FORMAT(CREATIONTIME, 'MM'),
fORMAT(CREATIONTIME, 'MMM'),
fORMAT(CREATIONTIME, 'MMMM'),
FORMAT(CREATIONTIME, 'yy'),
fORMAT(CREATIONTIME, 'yyy'),
fORMAT(CREATIONTIME, 'yyyyy'),
format(creationtime,'dd/MM/yyyy','ja-JP')
FROM SALES.Orders


-- show creationtime using the following format:
-- day wed jan q1 2025 12:34:56PM
SELECT
CREATIONTIME,
'DAY ' + FORMAT(CREATIONTIME,'ddd MMM') + CONCAT(' q',DATEPART(QUARTER, CREATIONTIME)) + FORMAT(CREATIONTIME,' yyyy  hh:mm:ss tt')
FROM SALES.Orders


-- DATE AGGREGATIONS
SELECT
FORMAT(ORDERDATE, ' MMM - yy') AS ORDERDATE,
COUNT(*) AS NUMBER_OF_ORDERS
FROM SALES.Orders
GROUP BY FORMAT(ORDERDATE, ' MMM - yy')


-- CONVERT
 -- CONVERST DATE AND TIME TO ANOTHER VALUE
 
 SELECT 
 CONVERT(INT, '123') AS STR_TO_INT,
 CONVERT(DATE, '2025-08-20') AS STR_TO_DATE,
 CREATIONTIME,
 CONVERT(DATE, CREATIONTIME) AS DATETIME_TO_DATE,
 CONVERT(VARCHAR, CREATIONTIME, 32) AS USA_STD32,
 CONVERT(VARCHAR, CREATIONTIME, 34) AS EURO_STD34
 FROM SALES.Orders

 -- CAST
 SELECT
 CAST('2020-08-20' AS DATE) AS STR_TO_DATE,
  CAST('2020-08-20' AS DATETIME) AS STR_TO_DATETIME,
   CAST(CREATIONTIME AS DATE) AS DATETIME_TO_DATE,
 CAST('123' AS INT) AS STR_TO_INT,
 CAST(123 AS VARCHAR) AS INT_TO_STR
 FROM SALES.Orders


 -- DATE ADD
	-- ADDS OR SUBTRACTS A SPECIFIC TIME INTERVAL TO/FROM A DATE
SELECT
orderid,
orderdate,
dateadd(year, 2, orderdate) as TWO_YEAR_JUMP,
DATEADD(MONTH, 3, ORDERDATE) AS '3_MONTH_JUMP',
DATEADD(DAY, -10, ORDERDATE) AS '10 DAY BACK'
from sales.Orders

--DATEDIFF
	-- FIND THE DIFFERENCE BETWEEN TWO DATES

SELECT 
ORDERDATE,
SHIPDATE,
DATEDIFF(DAY, ORDERDATE, ShipDate) AS LAG_DAYS
FROM SALES.Orders

-- CALCUALTE THE AGE OF EMPLOYEES
SELECT
FIRSTNAME,
BIRTHDATE,
DATEDIFF(YEAR, BIRTHDATE, GETDATE()) AS AGE
FROM SALES.Employees

-- FIND THE AVERAGE SHIPPING DURATION IN DAYS FOR EACH MONTH 
SELECT
FORMAT(ORDERDATE, 'MMM') AS MONTH,
AVG(DATEDIFF(DAY, OrderDate, ShipDate)) AS AVG_SHIPPING_DURATION
FROM SALES.ORDERS
GROUP BY FORMAT(ORDERDATE, 'MMM')


-- TIME GAP ANALYSIS
-- FIND THE NUMBER OF DAYS BETWEEN EACH ORDER AND THE PREVIOUS ORDER
SELECT
ORDERID,
ORDERDATE AS CURRENT_ORDERDATE,
LAG(ORDERDATE) OVER (ORDER BY ORDERDATE) AS PREVIOUS_ORDERDATE,
DATEDIFF(DAY, ORDERDATE, LAG(OrderDate) OVER (ORDER BY ORDERDATE)) AS DIFF_BETWEEN_ORDERDATE
FROM SALES.ORDERS


-- ISDATE
-- CHECK IF A VALUE IS DATE
 -- 1 - VALID DATE, 0 - IF NOT A VALID DATE

 SELECT
ISDATE('2025-08-20'),
ISDATE(1223123123),
ISDATE('123'),
ISDATE('MONDAY THE THIRD'),
ISDATE('2025'),
ISDATE('01-13-1998')

--

SELECT
ORDERDATE,
ISDATE(ORDERDATE),
 CASE WHEN ISDATE(ORDERDATE) = 1 THEN CAST(ORDERDATE AS DATE)
	ELSE '9999-01-02' /* THE ELSE CONVERTS THE NON ELIGIBLE VALUE INTO THE ELSE DEFAULT*/
 END NEWORDERDATE
 FROM 
(
	SELECT '2025-08-20' AS ORDERDATE UNION
	SELECT '2025-08-21' UNION
	SELECT '2025-08-22' UNION
	SELECT '2025-08-23' UNION
	SELECT '2025-08-'
)t
--WHERE ISDATE(ORDERDATE) = 0 /* RETRIEVES ALL THE NULL/ NON-DATE ELIGIBLE UNITS*/